Coletor MPRN: agora utilizando o novo layout!
dadosjusbr/coletor-mprn pull request #1
Opened 2021-11-23 11:31 UTC by marcos-inja

## MPRN utilizando o novo layout
> Esse **pr** atualiza o coletor **mprn**

2021-11-26 18:51 UTC, danielfireman requested changes

2021-11-26 18:51 UTC, danielfireman commented on src/data.py
> +                f"./output/Membros ativos{self.month}-{self.year}.ods"
Normalizar os nomes dos arquivos: sugestão `membros-ativos-01-2020.ods`


Aqui e abaixo

2021-11-26 18:51 UTC, danielfireman commented on src/main.py
> +    output_path = "./output"
```suggestion
    output_path = "/output"
```

2021-11-29 14:15 UTC, danielfireman reviewed
@joaolgm poderia olhar os metdados, por favor?

2021-11-29 15:04 UTC, joaolgm commented on src/metadado.py
> +        metadado.formato_consistente = False
Creio que nesse caso o formato_consistente deve ser TRUE. As planilhas seguem com as mesmas coluna sempre, acho que o fato de que a partir de 2020 ser utilizada uma planilha a mais quebre a consistência somente naquele mês(01/2020)

2021-11-30 12:08 UTC, joaolgm approved these changes

2021-11-30 13:49 UTC, merged